/**
 * Do not edit directly
 * Generated on Thu, 09 Feb 2023 19:41:17 GMT
 */

export const posterPosterlarge = {"fontSize":64,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-2.5,"lineHeight":58,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const posterPostermedium = {"fontSize":54,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-2.25,"lineHeight":54,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const posterPostersmall = {"fontSize":48,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-2.25,"lineHeight":50,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const posterPosterxs = {"fontSize":36,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-2,"lineHeight":38,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const headersHerobold = {"fontSize":36,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-0.5,"lineHeight":42,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const headersHeronormal = {"fontSize":36,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-0.5,"lineHeight":42,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const headersHeaderbold = {"fontSize":28,"textDecoration":"none","fontFamily":"SF Pro Display","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-0.5,"lineHeight":34,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const headersHeadernormal = {"fontSize":28,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-1,"lineHeight":32,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const headersSectiontitle = {"fontSize":24,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-0.85,"lineHeight":28,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const headersSubtitle = {"fontSize":18,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":24,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const textBodytitlelarge = {"fontSize":16,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":22,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const textBodylargebold = {"fontSize":16,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":22,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const textBodylarge = {"fontSize":16,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":400,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":22,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const textBodytitlesmall = {"fontSize":13,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":18,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const textBodysmall = {"fontSize":13,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":400,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":18,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const supportingCaption = {"fontSize":12,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":400,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0.15,"lineHeight":16,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const supportingCaptionbold = {"fontSize":12,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0.15,"lineHeight":16,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const supportingLabel = {"fontSize":11,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":700,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0.15,"lineHeight":14,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"uppercase"};
export const supportingBadge = {"fontSize":11,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":16,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const interactiveButtonlarge = {"fontSize":16,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0,"lineHeight":24,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const interactiveButtonsmall = {"fontSize":12,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":0.15,"lineHeight":16,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};
export const navigationNavigationtitle = {"fontSize":18,"textDecoration":"none","fontFamily":"SF Pro Text","fontWeight":500,"fontStyle":"normal","fontStretch":"normal","letterSpacing":-0.25,"lineHeight":28,"paragraphIndent":0,"paragraphSpacing":0,"textCase":"none"};